### ISSUE TITLE
1.21 Crashes with Wilder Wild.

### ISSUE THREAD

**Issue by makumaku1974** [SolidBlock-cn/extshape#48] opened 2024-06-22 01:28 UTC
CRASH LOG:
[crash-2024-06-21_17.47.41-client.txt](https://github.com/user-attachments/files/15926196/crash-2024-06-21_17.47.41-client.txt)

LOG:
[2024-06-21-6.log.gz](https://github.com/user-attachments/files/15926198/2024-06-21-6.log.gz)

The issue is they use BuiltinRegistries in pers.solid.brrp.v1.impl.RuntimeResourcePackImpl, which crashes any time there's any modded content.

**Comment by SolidBlock-cn** [comment] 2024-07-01 03:43
Duplicate of #46, though in different game versions.

**Closed as not planned by SolidBlock-cn** 2024-07-01 03:43 UTC
Labels: duplicate
