### ISSUE TITLE
[Crash] Extended Block Shapes causing crash when Wilder Wild is also installed.

### ISSUE THREAD

**Issue by Gamemassa** [SolidBlock-cn/extshape#52] opened 2024-07-15 15:20 UTC
**Version**
- Minecraft 1.21
- Fabric Loader 0.16.0
- Fabric API 0.100.7
- Extended Block Shapes 2.1.4

**Description**
I already had Extended Block Shapes in my custom modpack and I added Wilder Wild, and my game crashed on startup. I mentioned this in the [Wilder Wild issues thread](https://github.com/FrozenBlock/WilderWild/issues/399), and they said the issue appears to be on Extended Block Shapes' end. They also mentioned that it was a duplicate of [this issue](https://github.com/FrozenBlock/WilderWild/issues/391), and in that thread someone said it's fixed with the latest version of BRRP, but I'm already using the latest version of that and it's still happening.

**Logs**
- Crash Report:
https://mclo.gs/zVhXnE2

- Latest.log:
https://mclo.gs/qrnmxXo

**Comment by SolidBlock-cn** [comment] 2024-07-16 02:20
Thank you for the post. It's duplicate of #46.

**Closed as not planned by SolidBlock-cn** 2024-07-16 02:20 UTC
Labels: duplicate

**Comment by SolidBlock-cn** [comment] 2024-07-16 02:22
The *latest version* you mentioned is not released, but just a pre-release. I didn't release that because it was still not stable enough and may also contain some minor issues. If willing, you can try downloading the pre-release and testing.

**Comment by Gamemassa** [comment] 2024-07-16 11:47
> The _latest version_ you mentioned is not released, but just a pre-release. I didn't release that because it was still not stable enough and may also contain some minor issues. If willing, you can try downloading the pre-release and testing.

Oh, my apologies. I completely forgot to check the releases on GitHub to see if there was a new one. I'll give that a try.
